### ISSUE TITLE
Test_p2p stucks on finding route state on different routers

### ISSUE THREAD

**Issue by LeventSevgili** [ValveSoftware/GameNetworkingSockets#149]
Hello,

Here is another test!

I have built the latest up to date GNS and built it with vs 2019 latest with CMake.

We setup a signal server on a public server, which we can easily connect.

The test is simple, this time, me and my friend on different routers tries to connect each other with the test_p2p server and client.

We got below log for server:

```
C:\Users\Umut\Desktop\testRelease>test_p2p.exe --server --identity-local str:identity1
- 0.002126 Initialized low level socket/threading support.
- 0.060907 Creating listen socket, local virtual port 0
- 12.310433 Creating signaling session for peer 'str:levent'
- 12.310614 [#2836128063 P2P str:levent] Accepting
- 12.320928 [#2836128063 P2P str:levent] finding route
- 22.311886 [#2836128063 P2P str:levent] problem detected locally (5008): Timed out attempting to negotiate rendezvous
- 22.313882 [#2836128063 P2P str:levent] problem detected locally, reason 5008: Timed out attempting to negotiate rendezvous
- 22.315307 Shutting down low level socket/threading support.
```
and we got below log for client

```
C:\Users\loren\Desktop\Source\GameNetworkingSockets\bin\bin\Release>test_p2p.exe --client --identity-local str:levent --identity-remote str:identity1
  0.001665 Initialized low level socket/threading support.
  0.065937 Connecting to 'str:identity1', virtual port 0, from local virtual port 0.
  0.066030 Creating signaling session for peer 'str:identity1'
  0.068645 [#3484819731 P2P str:identity1] Entered connecting state
  0.255163 [#3484819731 P2P str:identity1] finding route
  0.255258 [#3484819731 P2P str:identity1] finding route
 10.247192 [#3484819731 P2P str:identity1] closed by peer
 10.247254 [#3484819731 P2P str:identity1] closed by peer, reason 5008: Timed out attempting to negotiate rendezvous
 10.248985 Shutting down low level socket/threading support.
```

It seems we have a connection somehow but it stucks at finding route state. Then times out.

On the other hand when i run the server and client on my pc, they connect without a problem.
Any idea? 
Thank you very much!

**Comment by fletcherdvalve** [comment]
Finally got all setup to build and run this on Windows, sorted out a bunch of other issues, and the good news is that I can now actually reproducing this!  Even when both clients are on my own machine.  Linux works perfectly, obviously.

**Comment by fletcherdvalve** [comment]
OK, after fixing a few issues with debug builds and windows builds with the new webrtc (slightly newer than the one we are using on steam), I have my linux box connecting to my linux box.  But the expected messages are never exchanged.  So something still not 100% right here, so I'll keep this issue open.

**Comment by fletcherdvalve** [comment]
This is fixed by 0e5a5ff83132c71d69fcac0326756aff7a08f233

Still some issues to work out with calling some webrtc accessors from the "wrong" thread (which used to be legal, since they just accessed a flag), but I am pretty sure this particular issue is fixed.

**Comment by LeventSevgili** [comment]
Well i still have the following logs, (i'm pretty sure i pulled the latest and rebuilt the GNS, checked the dll create time).  and we are on Win 10 platform.


Server log
```
C:\Users\gkdnz\Desktop\testP2P>test_p2p.exe --server --identity-local str:identity1
  0.002171 Initialized low level socket/threading support.
  0.009635 Creating listen socket, local virtual port 0
 19.887108 Creating signaling session for peer 'str:levent'
 19.887297 [#1232126326 P2P str:levent] Accepting
 19.897644 [#1232126326 P2P str:levent] finding route
 29.888972 [#1232126326 P2P str:levent] problem detected locally (5008): Timed out attempting to negotiate rendezvous
 29.890032 [#1232126326 P2P str:levent] problem detected locally, reason 5008: Timed out attempting to negotiate rendezvous
 29.891563 Shutting down low level socket/threading support.
```

client log
```
C:\Users\loren\Desktop\Source\GameNetworkingSockets\bin\bin\Release>test_p2p.exe --client --identity-local str:levent --identity-remote str:identity1
  0.001572 Initialized low level socket/threading support.
  0.007567 Connecting to 'str:identity1', virtual port 0, from local virtual port 0.
  0.007673 Creating signaling session for peer 'str:identity1'
  0.010049 Sending msg 'Greetings!'
  0.010173 [#1703147576 P2P str:identity1] Entered connecting state
  0.251140 [#1703147576 P2P str:identity1] finding route
  0.251254 [#1703147576 P2P str:identity1] finding route
 10.252210 [#1703147576 P2P str:identity1] problem detected locally (5008): Timed out attempting to negotiate rendezvous
 10.252342 [#1703147576 P2P str:identity1] problem detected locally, reason 5008: Timed out attempting to negotiate rendezvous
 10.254002 Shutting down low level socket/threading support.
```

**Comment by fletcherdvalve** [comment]
I have fixed the threading issue, and I was looking into this one, and I'm not reproducing any problems any more.

When I run the code right now, I get very detailed output from WebRTC as it is enumerating and sharing candidates.  I don't suppose you could try again, and if it fails, share the logs from both sides, so we can see what candidates are being gathered and shared?

**Comment by LeventSevgili** [comment]
Hey Fletcher,

I did a retest with the very same setup with a friend outside of my network.

It did worked! Here i'm delivering the logs from the server and client "test_p2p.exe" app.

Server log:

```
C:\Users\loren\Desktop\Source\GameNetworkingSockets\bin\bin\Release>test_p2p.exe --server --identity-local str:identity1
  0.001522 Initialized low level socket/threading support.
  0.007698 Creating listen socket, local virtual port 0
 23.325765 Creating signaling session for peer 'str:levent'
 23.325919 [#1571415768 P2P str:levent] Accepting
 23.336249 Waited 5.4ms for SteamNetworkingSockets lock [ServiceThread]
 23.339035 [#1571415768 P2P str:levent] finding route
 23.757343 Received message 'Greetings!'
 23.757616 Sending msg 'I got your message'
 23.793226 [#1571415768 P2P ICE str:levent] connected
 23.795344 [#1571415768 P2P ICE str:levent] connected
 24.140007 [#1571415768 P2P ICE str:levent] closed by peer
 24.142735 [#1571415768 P2P ICE str:levent] closed by peer, reason 1000: Test completed OK
 24.145177 Waiting for any last cleanup packets.
 25.149180 Shutting down low level socket/threading support.
```

Client log:

```
$ ./test_p2p.exe --client --identity-local str:levent --identity-remote str:identity1
  0.001901 Initialized low level socket/threading support.
  0.008384 Connecting to 'str:identity1', virtual port 0, from local virtual port 0.
  0.008511 Creating signaling session for peer 'str:identity1'
  0.010537 Sending msg 'Greetings!'
  0.010657 [#1354322291 P2P str:identity1] Entered connecting state
  0.289544 [#1354322291 P2P str:identity1] finding route
  0.289783 [#1354322291 P2P str:identity1] finding route
  0.596276 [#1354322291 P2P ICE str:identity1] connected
  0.599247 [#1354322291 P2P ICE str:identity1] connected
  0.672172 Received message 'I got your message'
  0.672316 Closing connection and shutting down.
  0.672537 Waiting for any last cleanup packets.
  1.673781 Shutting down low level socket/threading support.

```

Thank you for the follow up! I'm closing the issue.

**Comment by fletcherdvalve** [comment]
I have no idea what fixed it, honestly.  If you find any new problems, please let me know!
